### ISSUE TITLE
Cannot find environment ID values

### ISSUE THREAD

**Issue by njcorona** [IBM/cognos-analytics-using-unstructured-data#56]
Hi,

I'm working through this document, and I'm having trouble on step 4: Add servcie credentials to environment files.

The README says: "From your Discovery service collection page, locate the credentials for your collection by clicking the dropdown button located at the top right. Copy the Collection ID and Environment ID values."  I do not see this dropdown available when I am on the collection.

This is the page where I am looking for the dropdown.  

![image](https://user-images.githubusercontent.com/43733460/88309401-4292a680-ccdc-11ea-9b45-d23505611a48.png)

Am I looking in the wrong place?  Any guidance would be much appreciated.  I am working on the Discovery-OM-Premium instance with the "CCI Demo Data" and "CCI Demo Data 2" collections.

**Comment by rhagarty** [comment]
@njcorona the instructions are for running Discovery on IBM Cloud, but you are running on Cloud Pak for Data. Do you have access to an Disco instance on IBM Cloud?

If not, I can try to work with you to get this working - it will require changing some of the scripts.

**Comment by njcorona** [comment]
Gotcha.  I'm working with Discovery's Content Miner, so I have to use a Premium instance.  In my understanding, Discovery-OM-Premium is the only Premium instance I can get access to, so I don't think I can get access to Content Miner on IBM Cloud.

That would be great!  Is there anything I can do on my end to help?

**Comment by rhagarty** [comment]
any specific reason you need to use Content Miner? It's real easy to create an IBM trial account and provision a free version of Discovery

https://www.ibm.com/cloud

**Comment by njcorona** [comment]
Yep, I'm trying to sketch out a demo for a new sales pattern of Content Miner + Cognos.

**Comment by rhagarty** [comment]
You at IBM? If so, contact me on Slack
